# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kc < Formula
  desc "Human-friendly macOS Keychain CLI"
  homepage "https://github.com/v-gutierrez/kc"
  version "0.4.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/v-gutierrez/kc/releases/download/v0.4.0/kc-darwin-amd64.tar.gz"
    sha256 "50e164596bbe1ed1ec00065ab21d5d6c0b174e5bb0ab7168819231b18e682274"

    def install
      bin.install "kc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/v-gutierrez/kc/releases/download/v0.4.0/kc-darwin-arm64.tar.gz"
    sha256 "85a30df94a59c4935a31a73eba5ecff8f132ddcf836357d4b20d3c8f2a813f11"

    def install
      bin.install "kc"
    end
  end

  test do
    system "#{bin}/kc", "--version"
  end
end
