# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kc < Formula
  desc "Human-friendly macOS Keychain CLI"
  homepage "https://github.com/v-gutierrez/kc"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/v-gutierrez/kc/releases/download/v1.0.0/kc-darwin-amd64.tar.gz"
    sha256 "cc4e5ccf5407242cd8891b8c44fceb7fbdfdd1c5e92c8e9c059b4fab091a3edd"

    define_method(:install) do
      bin.install "kc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/v-gutierrez/kc/releases/download/v1.0.0/kc-darwin-arm64.tar.gz"
    sha256 "3957340d03565ced300ce805245f73664ec0cd10d79015f6ea1512a68144cc30"

    define_method(:install) do
      bin.install "kc"
    end
  end

  test do
    system "#{bin}/kc", "--version"
  end
end
